### ISSUE TITLE
Function returns only one scored image when multiple images are sent

### ISSUE THREAD

**Issue by markdturner** [NewcastleRSE/mousemapp-predict-function#4]
**Describe the bug**
 Currently, only one image is returned despite multiple images being uploaded. The code that should handle this is at: https://github.com/NewcastleRSE/mousemapp-predict-function/blob/a9e5653bbc0f925bd60e32648438f4496419623f/predict/__init__.py#L36 

**To Reproduce**
1. Setup a POST request to `https://mousemapp.azurewebsites.net/api/predict?code=72zqkChgmomeOZmmwH_-wT1fg6nxykamnJTExzALnKccAzFufDWatg==`
2. Create the request body with the following inputs
<img width="853" alt="Screenshot 2023-04-11 at 11 03 56" src="https://user-images.githubusercontent.com/6863551/231128755-eb5d797d-d29a-4fdc-b688-c01ec35638cd.png">

4. Submit the request
5. See the response only includes data for one file.

**Expected behavior**
The function should support an array of files being uploaded, compute the BCS score for each one and return an average score as well as a score per image.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 112.0.5615.49

**Additional context**
The problem occurs from both the website and when called directly using Postman.

**Comment by mdsimpson42** [comment]
I can't see anything obvious...

Probably stupid questions, but:
- Can you tell if it's always the first (or last) image in the list that gets returned? That would give a clue as to whether something is being overwritten or if the loop is exiting early. 
- Can you do a log in the loop to check that it is being called multiple times?

**Comment by tiagosousagarcia** [comment]
I only gave it a cursory look, but can go a bit deeper later on if it's still unresolved.

Nothing immediately jumps to me either, so I think logging the loop is crucial.

The only thing I can see is that it appears that the function will return 'Invalid image detected' if *any* image in the list is invalid -- is that the intended behavior? i.e., this:
```
else:
            return func.HttpResponse(
                json.dumps({'message': 'Invalid image detected'}),
                status_code=415,
                headers={"Content-Type": "application/json"}
            )
```
is inside the `for` loop, so it will exit before going through the rest of the images.

Otherwise, I know you didn't ask for this, but there are a couple of opportunities for optimization:
- Some image classification models will allow you to send an array of images for classification and return an array of results; or, at the very least,
- The model load stuff should be outside of the loop, otherwise you're reloading (or attempting to, it might cancel if the model is already in memory) n times for n images. You only need to repeat the eval bits

**Comment by markdturner** [comment]
@mdsimpson42 thanks for the idea of checking which image was working, it's what led me to realise that Azure functions don't support array-based form data, so instead of the key `files` being an array of three files it was overwriting each time so that the last file was the only one working. I've fixed it by passing the images as three separate form data values.

@tiagosousagarcia thanks for the optimisation tips, I can't believe I didn't spot that model loading inefficiency!
